export const DATE_FORMAT = 'YYYY-MM-DD';
export const DATE_TIME_FORMAT = 'YYYY-MM-DDTHH:mm';
export const DELIVERY_SENT_KEY = 'DELIVERY_SENT';
export const DELIVERY_RECEIVED_KEY = 'DELIVERY_RECEIVED';
export const DELIVERY_DRAFT_KEY = 'DELIVERY_DRAFT';

export const MEETING_SENT_KEY = 'MEETING_SENT';
